config/routes.rb
Rails.application.routes.draw do
  get 'profiles/profile'

  resource :profile, except: [:destroy]
  root "orders#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plates
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  board      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Order < ApplicationRecord
  has_and_belongs_to_many :plates
  belongs_to :user
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id             :integer          not null, primary key
#  description    :string
#  imageable_type :string
#  imageable_id   :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true 

end

app/models/plate.rb
# == Schema Information
#
# Table name: plates
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  price       :decimal(10, 2)
#  available   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Plate < ApplicationRecord
  has_and_belongs_to_many :orders
  has_many :pictures, as: :imageable
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  name       :string
#  last_name  :string
#  rol        :string
#  salary     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Profile < ApplicationRecord
  belongs_to :user
  has_many :pictures, as: :imageable
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    #byebug
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order # => vuelve al order_path(@order.id)
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])

  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order

    else
      render :edit
    end
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_path
  end

private

def order_params
  params.require(:order).permit(:board, :user_id)

end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

before_action :authenticate_user!
before_action :check_rol

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
      if @profile.update(profile_params)
        redirect_to profile_path
      else
        render :edit
      end
  end

  def new
# pasarle siempre un @model = Model.new  para enlazarlo al form_for
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to :profile
   else
        render :new
    end


  end

private

def profile_params
  params.require(:profile).permit(:name, :last_name, :rol, :salary).merge(user: current_user)
end

def check_rol
    # para chequear el rol
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">

          </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li> <%= current_user.email %> </li>
           	<li>
           		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
           	</li>
          <% else %>
           	<li>
           		<%= link_to('Login', new_user_session_path)  %>
           	</li>
            <li>
           		<%= link_to('Registrarse', new_user_registration_path)  %>
           	</li>
           <% end %>
        </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xs-8">
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do  |f| %>
  <%= f.label :board %>
  <%= f.text_field :board %>
  <%= f.label :user_id %>
  <%= collection_select(:order, :user_id, User.all, :id, :email, prompt: true) %>
  
  <%= f.submit %>
<% end %>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>
<%= render 'form' %>

app/views/orders/index.html.erb
<!-- <h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p> -->
 <!-- <%= @orders.inspect %> -->
<h2>Ordenes</h2>

<%= link_to "Nueva Orden", new_order_path %>

<hr>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>Mesero</th>
      <th>Mesa</th>
      <th>Detalle</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= "Nombre" %></td>
      <td><%= order.board %></td>
      <td><%= link_to "D", order_path(order) %></td>
      <td><%=  link_to "E", edit_order_path(order) %></td>
       <td><%= link_to "X", order_path(order), method: :delete, data: {confirm: "Estas seguro?"} %></td>
      <td><%= %></td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>
<%= render 'form' %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>
<%= @order.inspect%>

app/views/profiles/_form.html.erb
<%= form_for(@profile, url: profile_path) do |f| %>

  <% if @profile.errors.any? %>
    <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li> <%= msg.to_s %> </li>
      <% end %>
    </ul>
  <% end %>

<%= %>
<%= f.label :name %>
<%= f.text_field :name %> <br>

<%= f.label :last_name %>
<%= f.text_field :last_name %> <br>

<%= f.label :rol %>
<%= f.text_field :rol %> <br>

<%= f.label :salary %>
<%= f.number_field :salary %> <br>

<%= f.submit %>

<% end %>

app/views/profiles/edit.html.erb
<%= render "form" %> 

app/views/profiles/new.html.erb
<%= render "form" %> 

app/views/profiles/show.html.erb
<h1>Encuentrame en views/profiles/show.html.erb</h1>


<% if @profile  %>
    <%= @profile.inspect %> <br>

    <%= @profile.name %>
    <%= @profile.last_name %>
    <%= @profile.rol %>
    <%= @profile.salary %>

    <%= link_to "Editar Perfil", edit_profile_path(@profile) %>
  <% else %>
    <%= link_to "Crear Nuevo Perfil", new_profile_path %>
<% end %>

<hr>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>